config/routes.rb
Rails.application.routes.draw do
  resources :projects

  devise_for :users

  root 'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Read
    # Create
    # Update
    # Destroy
    if user.user_type == "CEO"
      # can :read, Homework, course_id: current_user.courses.map(&:id)
      can :read, Project, name: ["Google", "Yahoo"], description: ["Dude man sup"]
      can :create, Project
      can :update, Project
      can :destroy, Project
    elsif user.user_type == "Developer"
      can :read, Project
    elsif user.user_type == "Project Manager"
      can :read, Project
      can :create, Project
      can :update, Project
    end
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  USER_TYPES = ["Developer", "Project Manager", "CEO"]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:email, :password, :password_confirmation, :user_type)}

    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:email, :password, :password_confirmation, :user_type, :current_password)}

  end

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to projects_path, :alert => exception.message
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    authorize! :read, Project
    @projects = Project.accessible_by(current_ability)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    authorize! :read, Project
  end

  # GET /projects/new
  def new
    authorize! :create, Project
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
    authorize! :update, Project
  end

  # POST /projects
  # POST /projects.json
  def create
    authorize! :create, Project
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    authorize! :update, Project
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    authorize! :destroy, Project
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/home/index.html.haml
%h1 CanCan Demo App

= link_to "Projects", projects_path

app/views/layouts/_devise_menu.html.haml
- if user_signed_in? 
  = link_to current_user.email, edit_user_registration_path
  = link_to('Logout', destroy_user_session_path, :method => :delete)
- else
  = link_to('Login', new_user_session_path)
  |
  = link_to('Sign up', new_user_registration_path)

app/views/layouts/_flash_messages.html.haml
%p.notice= notice
%p.alert= alert

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Cancan
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/devise_menu'
    = render 'layouts/flash_messages'
    = yield

app/views/projects/_form.html.haml
= form_for(@project) do |f|
  - if @project.errors.any?
    #error_explanation
      %h2
        = pluralize(@project.errors.count, "error")
        prohibited this project from being saved:
      %ul
        - @project.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :description
    %br/
    = f.text_area :description
  .actions
    = f.submit

app/views/projects/edit.html.haml
%h1 Editing project
= render 'form'
= link_to 'Show', @project
|
\#{link_to 'Back', projects_path}

app/views/projects/index.html.haml
%h1 Listing projects
%table
  %thead
    %tr
      %th Name
      %th Description
      %th{:colspan => "3"}
  %tbody
    - @projects.each do |project|
      %tr
        %td= project.name
        %td= project.description
        %td= link_to 'Show', project if can? :read, Project
        %td= link_to 'Edit', edit_project_path(project) if can? :update, Project
        %td= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } if can? :destroy, Project
%br/
= link_to 'New Project', new_project_path if can? :create, Project

app/views/projects/new.html.haml
%h1 New project
= render 'form'
= link_to 'Back', projects_path

app/views/projects/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @project.name
%p
  %strong Description:
  = @project.description
- if can? :update, Project
  = link_to 'Edit', edit_project_path(@project)
  |
\#{link_to 'Back', projects_path}